language: java
jdk:
- oraclejdk8
cache:
  directories:
  - ".autoconf" 
  - "$HOME/.m2" 
install: true
script: mvn clean install -DskipTests=true
notifications:
  slack: 
    rooms:
      secure: qqPiotswn0AzChN5JYMOWoHUGYYe9z9XdBg20M7bA0DxL36/fiFHuhUhdLY50MCBknxRdlep8zRVbOXSj2mE4rx+mCi0t2jA/xEn2Ff2XjahxLhJZSrV+fGjQ2t/Grh6VL8n8+izmN3JHuTK+Ibb0r5Qo6oimM9eV3Pb/IQW14Iov6AcMJGUvvPCuCFvJQ4JmXmRjEOp8sgg/Yu2PiUpqrld4f9UPtewYrAUCcZbeB4mu4ecSA87DSfx4I1VNbmTnrXYR3HwfdJRXzzqHQF8UAeJP5BNB8MZLT4WCBLT7FF2xyaBwmmsGhwgEjSK0X3M2SaTY7Vno0uCS+FuuL8AO/Q+98GJTnAYQimnlAw77tuJxS+ewyA5dDJxGmT0RR3N/CByP9UF3UQqINhosnBPxt3t/ocjlz2BXfjAI4UY3LnjotfjqoVHoEuTnt9u68ixw9D43ardl1A+5Qn9ckzjctZML0B4i3km2mcOwltNaTPwjRlFOPxQcTe6Vsk6ReTczUAJgxdGiABUiAvcPtuBIus8aCIm5F52oLrkm10YzNyjqK+SEZKLeZemPhQBEdvEtPOQFk/oCkz99bzvT2G0RAKvscdkljrRtxMYY8L+eIbsNIFvC5dTepLrqjXBbYmhEh/pvLElwuH634n3Y+bzxSxfb7uimQLHCr+/zM9Mvh8=
